# Generated by Django 4.2.4 on 2023-09-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='popularnewsall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newstitle', models.CharField(max_length=40)),
                ('newstitlematch', models.CharField(max_length=40)),
                ('newsheading', models.TextField(max_length=250)),
                ('newslink', models.TextField(max_length=250)),
            ],
        ),
    ]
