# Generated by Django 4.2.4 on 2023-09-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='ph',
            field=models.IntegerField(default=0),
        ),
    ]
