# Generated by Django 4.2.4 on 2023-09-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mypost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=400)),
                ('postimage', models.ImageField(upload_to='mypost/')),
                ('username', models.CharField(default='SOME STRING', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='SOME STRING', max_length=100)),
                ('last_name', models.CharField(default='SOME STRING', max_length=100)),
                ('email', models.EmailField(default='SOME STRING', max_length=254)),
                ('username', models.CharField(default='SOME STRING', max_length=100)),
                ('password', models.CharField(default='SOME STRING', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='userstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(choices=[('online', 'online'), ('offline', 'Offline'), ('Inmeeting', 'Inmeeeting')], default='online', max_length=20)),
            ],
        ),
    ]
